name = "shortkey"
main = "src/worker.ts"
compatibility_date = "2024-09-23"

# 静态前端资源目录 (Cloudflare Workers + Assets)
[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "shortkey-db"
database_id = "a213a412-df53-45fb-aadd-55efce0ed0d3"
